apiVersion: v1
kind: Service
metadata:
  name: flaskblog-service
spec:
  selector:
    app.kubernetes.io/name: flaskblog
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1283
